### ISSUE TITLE
Switch from robotjs to libnut

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/nut.js#86]
**Short overview**
Currently nut.js uses [octalmage/robotjs](https://github.com/octalmage/robotjs), a [nan](https://github.com/nodejs/nan) module. For easier support of multiple node versions, our [N-API](https://github.com/nodejs/node-addon-api) [port](https://github.com/nut-tree/libnut) should be elaborated.

**Use case**
Easier support for multiple node modules without recompiling the native module.

**Detailed description**

> N-API is an ABI stable C interface provided by Node.js for building native addons. It is independent from the underlying JavaScript runtime (e.g. V8 or ChakraCore) and is maintained as part of Node.js itself. It is intended to insulate native addons from changes in the underlying JavaScript engine and allow modules compiled for one version to run on later versions of Node.js without recompilation.

In [@nut-tree/libnut](https://github.com/nut-tree/libnut), [octalmage/robotjs](https://github.com/octalmage/robotjs) has been ported to N-API, which allows to use it with any node version >= 10 without having to recompile the native module.

**Comment by AdrianoFerrari** [comment]
Happy to have found nut.js. Any updates on when this will be merged?
Issues with the robotjs package is the main reason I started looking for alternatives...

**Comment by s1hofmann** [comment]
Hi @AdrianoFerrari,

with the new LTS version of node ([lts/erbium](https://nodejs.org/en/about/releases/)), I'm about to release a new version of nut.js quite soon (next week-ish). I'm just currently finishing up on some other tasks.

For now [@nut-tree/libnut](https://www.npmjs.com/package/@nut-tree/libnut) is basically an N-API port of robotjs with minor changes from my side. May I ask which issues have you been dealing with?

**Comment by s1hofmann** [comment]
@AdrianoFerrari I published nut.js v1.3.1 today which closes this issue.

**Comment by AdrianoFerrari** [comment]
Thanks, seems to install properly now on Travis for macOS and linux. Sorry I can't pinpoint what the issue was with robotjs vs libnut. Quick reading shows me that it's possible that robotjs was expecting an older JS engine (I remember the errors having something to do with "V8")...

Anyway, installs now :+1: 

(still having issues getting it to send keyboard commands on macOS on Travis, but that's very likely something I'm doing wrong... will keep at it).

**Comment by s1hofmann** [comment]
@AdrianoFerrari Happy to hear! 👍 

robotjs only provides prebuilt bindings up until node 8, so this might be causing errors in case a manual rebuild fails. libnut relies on N-API bindings which are compatible with any node major version >= 10 without recompiling.

Regarding errors on Travis: You might check which macOS version is used for the build. In recent versions of macOS (not 100% sure, but it might be Sierra and later) you have to explicitly grant accessibility rights to send e.g. keyboard events. On CI this might cause trouble. 
Would be interested in your findings, mind updating this issue in case of news?

**Comment by AdrianoFerrari** [comment]
You're right, macOS version seems to be the issue.

This [build](https://travis-ci.org/AdrianoFerrari/gingko-client-trytravis/jobs/607397193), with macOS macOS 10.14 (`osx_image: xcode10.2`) **fails**.

This [build](https://travis-ci.org/AdrianoFerrari/gingko-client-trytravis/jobs/607397193), with macOS macOS 10.13 (`osx_image: xcode10.1`) **succeeds**.

I'll post back if I find a workaround for newer macOS versions, but isn't looking promising so far...
